version: "3"
services:
  api:
    image: lab-app-api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    command: npm run start:api

  proxy:
    image: lab-app-proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
    command: npm run start:proxy-docker
